/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-06-02 14:08:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSPDB;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import java.io.*;
import java.util.*;
import java.net.*;

public final class newInsertDB_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<meta http-equiv = \"Content-Type\" content = \"text/html; charset = utf-8\" />\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!--java import-->\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    	<meta charset=\"UTF-8\"> <!--인코딩 설정 UTF-8-->\r\n");
      out.write("    	<style>\r\n");
      out.write("    		@font-face {\r\n");
      out.write("                font-family: \"D2CodingLigature\";\r\n");
      out.write("                src: url(./D2CodingLigature/D2CodingBold-Ver1.3.2-20180524-ligature.ttf) format(\"truetype\");\r\n");
      out.write("                font-weight: normal;\r\n");
      out.write("            }\r\n");
      out.write("            /*body 폰트 지정*/\r\n");
      out.write("            body{\r\n");
      out.write("                font-family: 'D2CodingLigature',serif;\r\n");
      out.write("            }\r\n");
      out.write("		  table {\r\n");
      out.write("		    border-collapse: collapse;\r\n");
      out.write("		    width : 75%\r\n");
      out.write("		  }\r\n");
      out.write("		  th, td {\r\n");
      out.write("		    border-bottom: 1px solid #444444;\r\n");
      out.write("		    padding: 10px;\r\n");
      out.write("		  }\r\n");
      out.write("		  th:first-child, td:first-child {\r\n");
      out.write("		    border-left: none;\r\n");
      out.write("		  }\r\n");
      out.write("		\r\n");
      out.write("		.fourth {\r\n");
      out.write("		  background: gold;\r\n");
      out.write("		  border-color: white;\r\n");
      out.write("		  color: black;\r\n");
      out.write("		  background-image: linear-gradient(45deg, yellow 50%, transparent 50%);\r\n");
      out.write("		  background-position: 100%;\r\n");
      out.write("		  background-size: 400%;\r\n");
      out.write("		  transition: background 300ms ease-in-out;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		.fourth:hover {\r\n");
      out.write("		  background-position: 0;\r\n");
      out.write("		}\r\n");
      out.write("		</style>\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write(" ");
    
 	try{
		//DB연동 
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/noheul","root","shdmf1030@");
        //Connection conn = DriverManager.getConnection("jdbc:mysql://192.168.23.60:3307/kopo11","root","shdmf1030@");
        Statement stmt = conn.createStatement();
        
        int maxID = 0;
        ResultSet settotal = stmt.executeQuery("select min(studentid) as minNum from jspDB where (studentid+1) not in (select studentid from jspDB);");
        while (settotal.next()) {
            maxID = settotal.getInt(1)+1;
        }
        
	    request.setCharacterEncoding("utf-8");
		String name = request.getParameter("name");
		String kor = request.getParameter("korean");
		String eng = request.getParameter("english");
		String mat = request.getParameter("mathmatic");
		
		stmt.execute("insert into jspDB (name, studentid, kor,eng,mat) values ('"+
		name + "',"+
		Integer.toString (maxID) +","+
		request.getParameter("korean")+","+
		request.getParameter("english")+","+
		request.getParameter("mathmatic")+");");
					
		stmt.close(); 
		conn.close(); 

      out.write("	<h1 align = center>성적 추가 입력 완료</h1>\r\n");
      out.write("	<form method = 'post' action = 'inputForm1.html'>	\r\n");
      out.write("		<table cellspacing=\"1\" width=\"400\" border=\"0\" align=\"center\" style=\"border-collapse: collapse;\">\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td width = 300></td>\r\n");
      out.write("				<td align=\"right\">\r\n");
      out.write("  				<input class=\"fourth\" type=\"submit\" value=\"뒤로 가기\" style=\"width: 70px; height: 40px; padding: 0px;font-weight: bold;\"></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("	</form>	\r\n");
      out.write("		</table>\r\n");
      out.write("		<table cellspacing=\"1\" width=\"400\" align=\"center\" >\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td bgcolor=\"gold\" width=\"100\" style=\"border-right: 1px solid #444444;\"><p align=\"center\"><strong>이름</strong></p></td>\r\n");
      out.write("				<td width = 300 style=\"border-left: 1px solid #444444;\"><p align=center><input value='");
      out.print(name);
      out.write("' style=\"width: 200px; height: 40px; padding: 0px;\"></p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				<td bgcolor=\"gold\" width=\"100\" style=\"border-right: 1px solid #444444;\"><p align=center><strong>학번</strong></p></td>\r\n");
      out.write("				<td width = 300 style=\"border-left: 1px solid #444444;\"><p align=center><input value='");
      out.print(maxID);
      out.write("' style=\"width: 200px; height: 40px; padding: 0px;\"></p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				<td bgcolor=\"gold\" width=\"100\" style=\"border-right: 1px solid #444444;\"><p align=center><strong>국어</strong></p></td>\r\n");
      out.write("				<td width = 300 style=\"border-left: 1px solid #444444;\"><p align=center><input value='");
      out.print(kor);
      out.write("' style=\"width: 200px; height: 40px; padding: 0px;\"></p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				<td bgcolor=\"gold\" width=\"100\" style=\"border-right: 1px solid #444444;\"><p align=center><strong>영어</strong></td>\r\n");
      out.write("				<td width = 300 style=\"border-left: 1px solid #444444;\"><p align=center><input value='");
      out.print(eng);
      out.write("' style=\"width: 200px; height: 40px; padding: 0px;\"></p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("				<td bgcolor=\"gold\" width=\"100\" style=\"border-right: 1px solid #444444;\"><p align=center><strong>수학</strong></p></td>\r\n");
      out.write("				<td width = 300 style=\"border-left: 1px solid #444444;\"><p align=center><input value='");
      out.print(mat);
      out.write("' style=\"width: 200px; height: 40px; padding: 0px;\"></p></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</table>	\r\n");
	}catch(Exception e) {
		System.out.println(e);
	}
 

      out.write("\r\n");
      out.write("		\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
